version: '3'

services:  
  api:
    build: ../
    entrypoint: ./.docker/entrypoint.sh
    container_name: server
    environment:
      NODE_ENV: development
    ports:
      - 4000:4000
    volumes:
      - ${PWD}/:/home/node/app 
    networks:
      - heelpy
networks:
  heelpy:
  
